services:
  fastapi:
    build: .
    ports:
      - 8000:8000
    environment:
      POSTGRES_URL: "postgresql+asyncpg://<username>:<password>@<db_host>:<db_port>/<db_name>"
      REDIS__HOST: "<redis_host>"
      REDIS__PORT: "<redis_port>"
